
name: bb-test

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project repo
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          bb: latest

      - name: Simple test
        env:
          BB_SRC=./bb/src/main
        run: |
          bb -f $BB_SRC/tester.clj
          # TODO
          # generate release json
          # regenerate all pages
          # need to boot strap pages from historical tags (won't have all details any more from Jenkins etc)
