
name: bb-test

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          bb: latest
#           bb: 0.8.2                    # Babashka
          
      - name: Simple test
        run: |
          bb -e '(.getAbsolutePath (clojure.java.io/file "."))'
          bb -e '(map #(.getName %) (file-seq (clojure.java.io/file ".")))'
          bb -e '(map #(.getName %) (file-seq (clojure.java.io/file "..")))'
#          bb -f ../bb/tester.clj
