name: Regenerate release docs

on:
  release:
    types: [published]
    
# on: workflow_dispatch
    
jobs:
  generate-release-docs:
    name: Regenerate the release docs
    runs-on: ubuntu-latest

    steps:
      - name: Find the release just created
        run: |
          echo action ${{ github.event.action }}
          echo release_id ${{ github.event.release.release_id }}
          echo tag ${{ github.event.release.tag }}
          echo name ${{ github.event.release.name }}
          echo author ${{ github.event.release.author }}
          echo author.name ${{ github.event.release.author.name }}
          echo author.login ${{ github.event.release.author.login }}
          echo payload ${{ github.event.release.payload }}
          echo payload ${{ github.event.release.payload }}
          echo payload ${{ github.event.release.payload.tag }}
          echo payload ${{ github.event.release.payload.release_id }}
          echo payload ${{ github.event.payload }}
          echo payload ${{ github.event.payload }}
          echo payload ${{ github.event.payload.tag }}
          echo payload ${{ github.event.payload.release_id }}
