name: Regenerate release docs

on:
  release:
    types: [published]
    
# on: workflow_dispatch
    
jobs:
  generate-release-docs:
    name: Regenerate the release docs
    runs-on: ubuntu-latest

    steps:
      - name: Find the release just created
        run: echo Regenerating release docs for ${{ github.event.release.release_id }}
