name: Generate release docs

on:
  release:
    types: [published]
    
# on: workflow_dispatch
    
jobs:
  generate-release-docs:
    name: Generate the release docs
    runs-on: ubuntu-latest

    steps:
      - name: Find the release just created
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo Generate release docs for ${{ github.event.release.tag_name }}

