name: Regenerate release docs

on:
  release:
    types: [published]
    
# on: workflow_dispatch
    
jobs:
  generate-release-docs:
    name: Regenerate the release docs
    runs-on: ubuntu-latest

    steps:
      - name: Find the release just created
        run: |
          echo action ${{ github.event.action }}
          echo release_id ${{ github.event.release.release_id }}
          echo tag ${{ github.event.release.tag }}
          echo name ${{ github.event.release.name }}
          echo author ${{ github.event.release.author }}
          echo isLatest ${{ github.event.release.isLatest }}
